name: Notify Microsoft 365

on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Notify on Push
        if: github.event_name == 'push'
        run: |
          curl -H "Content-Type: application/json" -d "{\"text\": \"ğŸ””ë©”ì¸ìœ¼ë¡œ ìƒˆë¡œìš´ push: ${GITHUB_REF} by ${GITHUB_ACTOR}. ì»¤ë°‹ ë©”ì‹œì§€: '${{ github.event.commits[0].message }}'.\"}" ${{ secrets.M365_WEBHOOK_URL }}
        env:
          GITHUB_REF: ${{ github.ref }}
          GITHUB_ACTOR: ${{ github.actor }}
      - name: Notify on Pull Request
        if: github.event_name == 'pull_request'
        run: |
          curl -H "Content-Type: application/json" -d "{\"text\": \"ğŸ”” ìƒˆë¡œìš´ pull request: ${{ github.event.pull_request.title }} by ${{ github.event.pull_request.user.login }}. Action: ${{ github.event.action }}, URL: ${{ github.event.pull_request.html_url }}.\"}" ${{ secrets.M365_WEBHOOK_URL }}
